repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(ts|tsx|js|jsx|json|css|md)$
        additional_dependencies:
          - prettier@3.2.5

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(ts|tsx|js|jsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-prettier@9.1.0
          - eslint-plugin-prettier@5.1.3
          - "@typescript-eslint/eslint-plugin@7.0.0"
          - "@typescript-eslint/parser@7.0.0"

  - repo: local
    hooks:
      - id: typescript-typecheck
        name: TypeScript Type Check
        entry: bash -c 'cd backend && bun run typecheck'
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$
